---
name: deploy

#on:
#  workflow_run:
#    workflows:
#      - 'learn-github-actions'
#    types:
#      - completed
on: [push]

jobs:
  deploy:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v5
        id: commit_at
        with:
          result-encoding: string
          script: |
            const commit_details = await github.rest.git.getCommit({owner: context.repo.owner, repo: context.repo.repo, commit_sha: context.sha});

            return commit_details.data.author.date;

      - run: echo "COMMIT_AT --- $COMMIT_AT -- DEPLOYMENT_AT -- $DEPLOYMENT_AT -- TTT -- $TTT --"
        env:
          COMMIT_AT: ${{ steps.commit_at.outputs.result }}
        shell: bash

#    name: Deploy ${{ matrix.project }} to ${{ matrix.env }}
#    runs-on: ubuntu-latest
#    strategy:
#      fail-fast: false
#      matrix:
#        env:
#          - env_a
#          - env_b
#        project:
#          - project_a
#          - project_b
#    steps:
#      - uses: actions/checkout@v2
#
#      - id: validate
#        uses: ./.github/actions/validate-env
#        with:
#          env: ${{ matrix.env }}
#          project: ${{ matrix.project }}
#
#      - if: fromJson(steps.validate.outputs.has-env)
#        uses: ./.github/actions/deploy
#        with:
#          run_db_migrations_env: ${{ steps.validate.outputs.run_db_migrations_env }}
#          env: ${{ matrix.env }}
#          project: ${{ matrix.project }}
